'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class RepeaterNavigateBar

    '''<summary>
    '''lblTotalRecord control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotalRecord As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''hdfCurrentSeq control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfCurrentSeq As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfCurrentCol control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfCurrentCol As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''imbFirst control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imbFirst As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''imbBack control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imbBack As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''lblCurrentPage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCurrentPage As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTotalPage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotalPage As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''imbNext control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imbNext As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''imbLast control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imbLast As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ddlPage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPage As Global.System.Web.UI.WebControls.DropDownList
End Class
